// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("N26DirectImport.FunctionsApp")]
[assembly: AssemblyProduct("N26DirectImport")]
[assembly: AssemblyVersion("1.9999.0.0")]
[assembly: AssemblyFileVersion("1.9999.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "N26DirectImport.FunctionsApp";
        internal const System.String AssemblyProduct = "N26DirectImport";
        internal const System.String AssemblyVersion = "1.9999.0.0";
        internal const System.String AssemblyFileVersion = "1.9999.0.0";
    }
}
